linters:
  enable:
  - gosec
  - godot
  - misspell
  - stylecheck

linters-settings:
  stylecheck:
    # Select the Go version to target. The default is '1.13'.
    go: "1.15"
    checks: ["all", "ST1*"]
    initialisms: ["ACL", "API", "ASCII", "CPU", "CSS", "DNS", "EOF", "GUID", "HTML", "HTTP", "HTTPS", "ID", "IP", "JSON", "QPS", "RAM", "RPC", "SLA", "SMTP", "SQL", "SSH", "TCP", "TLS", "TTL", "UDP", "UI", "GID", "UID", "UUID", "URI", "URL", "UTF8", "VM", "XML", "XMPP", "XSRF", "XSS"]

issues:
  exclude-use-default: false
  exclude:
  - "ST1000: at least one file in a package should have a package comment"


output:
  # colored-line-number|line-number|json|tab|checkstyle|code-climate, default is "colored-line-number"
  format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: false

  # print linter name in the end of issue text, default is true
  print-linter-name: true


