name: Pipeline Checks
on:
  push:
    branches: 
    - dev
jobs:
  format-check:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x 
      uses: actions/setup-go@v4
      with:
        go-version: ^1.20
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Run Format Check
      run: make check-format
    - name: Vet
      run: go vet ./... # <1>
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint
        uses: golangci/golangci-lint-action@v3
   #REMOVING TESTING AND BUILDING FROM PRE-MAIN Pipeline, just doesn't seem necesary at this point. Espcially because I use the Dev branch to get things ready for another pipeline that already had testing and building. I can easily put testing and app building back in the pipeline though. 
   